'use client';

import { useState } from 'react';

type Message = { role: 'user' | 'assistant'; content: string };
const profile = `김효제는 울산대학교 ICT융합학부 1학년으로, 2026년 1학기부터 여름방학까지 디자인과 개발을 함께 시도했다. 부모님 카페 코지커피의 포스터, 메뉴판 배너, 인스타그램 콘텐츠를 만들었고, React·TypeScript 기반 팀 프로젝트, OceanSnap 해양 쓰레기 AI 웹앱, Python 크롤러와 GitHub Actions를 이용한 학내 공지 Discord 자동 알림을 구현했다. Ada, Python, Java Spring Boot, JPA를 학습했고 TOPCIT 230점을 받았다.`;
const semesters = [
  { period: '1학기 시작 · 02–03', title: '디자인과 대학생활을 동시에 시작', text: '코지커피 리뉴얼 포스터·메뉴판 배너를 만들며 실제 사용자를 생각하는 디자인을 경험했습니다. 울산대학교 ICT융합학부에 입학하고 동아리에도 도전했습니다.', tags: ['코지커피', '입학', '동아리'], color: 'yellow' },
  { period: '1학기 학습 · 04–05', title: '관심을 기술의 언어로 넓히다', text: '음악과 공연을 콘텐츠로 기록하는 한편, Python 자료구조·웹 스크래핑·Spring Boot·JPA를 공부했습니다. 트랙페스타에서 전공과 선배들의 실제 이야기도 만났습니다.', tags: ['콘텐츠', 'Python', 'Spring Boot'], color: 'blue' },
  { period: '1학기 후반 · 06', title: 'AI를 바라보는 기준을 세우다', text: '졸업작품 전시에서 오류를 직접 지적하는 AI 시스템을 리뷰했습니다. “답하는 AI”를 넘어 사용자의 다음 행동을 돕는 AI를 만들고 싶다는 방향이 생겼습니다.', tags: ['AI 전시', '리뷰', '문제 정의'], color: 'purple' },
  { period: '여름방학 · 07–08', title: '배운 것을 실제로 작동시키다', text: '팀 프로젝트에서 React·Next.js·TypeScript·GitHub Actions·Docker를 사용했습니다. Python 크롤러와 GitHub Actions를 연결해 새 학내 공지를 Discord로 자동 전송했습니다.', tags: ['팀 프로젝트', '자동화', 'Discord'], color: 'teal' },
];
const projects = [
  { id: 'cozy', no: '01', type: 'REAL CLIENT / DESIGN', title: '코지커피 리뉴얼 콘텐츠', summary: '부모님 카페의 재오픈을 알리는 실제 콘텐츠를 만들었습니다.', did: '포스터·메뉴판 배너·인스타그램 콘텐츠 제작', how: '카페의 따뜻한 분위기와 메뉴 정보를 관찰한 뒤, 갈색 계열의 브랜드 톤과 읽기 쉬운 정보 배치를 적용했습니다.', result: '실제 매장과 SNS에 사용할 수 있는 디자인 결과물', image: '/evidence/cozycoffee-poster.png', thumb: '/evidence/cozycoffee-logo.png', tags: ['실제 의뢰', '시각 디자인', 'SNS'] },
  { id: 'meal', no: '02', type: 'TEAM / FRONTEND', title: '오늘의 식단 웹앱', summary: '팀 프로젝트로 React·TypeScript 기반 식단 화면을 제작했습니다.', did: '식단 홈 화면과 재사용 가능한 UI 컴포넌트 구현', how: '화면을 아침·점심·저녁 카드로 나누고, 사용자가 오늘의 메뉴와 예상 비용을 빠르게 파악하도록 정보 우선순위를 정했습니다.', result: '직접 눌러볼 수 있는 웹 화면과 협업 경험', image: '/evidence/vacation-project-home.png', thumb: '/evidence/ai-project-roadmap.png', tags: ['React', 'TypeScript', 'GitHub'] },
  { id: 'ocean', no: '03', type: 'AI / WEB PROTOTYPE', title: 'OceanSnap 해양 쓰레기 분석', summary: '해양 쓰레기 사진을 분석해 수거 우선순위를 제안하는 AI 웹앱을 구상했습니다.', did: '시민 신고 화면·분석 결과·관리자 대시보드의 사용자 흐름 설계', how: '신고 → 이미지 분석 → 결과 확인 → 관리자의 지도형 판단으로 이어지는 화면 구조를 만들고, AI 결과가 실제 행동으로 이어지도록 구성했습니다.', result: '사회문제를 기술로 풀어본 서비스 프로토타입', image: '/evidence/oceansnap-icon.png', thumb: '/evidence/ai-project-poster.png', tags: ['AI UX', 'Next.js', '서비스 기획'] },
  { id: 'notice', no: '04', type: 'PYTHON / AUTOMATION', title: '학내 공지 Discord 자동 알림', summary: '반복해서 공지사항을 확인하는 일을 코드로 줄였습니다.', did: 'Python 크롤러·새 글 판별·Discord 메시지 전송 구현', how: '공지 페이지를 주기적으로 읽고 이전 데이터와 비교해 새 글만 골라낸 뒤, GitHub Actions가 자동 실행하도록 연결했습니다.', result: '배운 Python을 실제 생활의 불편 해결에 적용', image: '/evidence/ai-project-roadmap.png', thumb: '/evidence/vacation-project-home.png', tags: ['Python', 'Web scraping', 'GitHub Actions'] },
];

export default function Home() {
  const [chatOpen, setChatOpen] = useState(false); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false);
  const [messages, setMessages] = useState<Message[]>([{ role: 'assistant', content: '안녕하세요. 저는 효제의 2026년 기록을 안내하는 AI 페르소나입니다. 어떤 프로젝트를 어떻게 만들었는지 물어보세요.' }]);
  const askBot = async (preset?: string) => { const prompt = (preset ?? input).trim(); if (!prompt || loading) return; setInput(''); setMessages((m) => [...m, { role: 'user', content: prompt }]); setLoading(true); try { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ prompt, context: profile }) }); const data = await res.json(); setMessages((m) => [...m, { role: 'assistant', content: data.message ?? '기록을 찾지 못했어요.' }]); } catch { setMessages((m) => [...m, { role: 'assistant', content: '잠시 후 다시 시도해 주세요.' }]); } finally { setLoading(false); } };
  return <main className="site-shell portfolio-page">
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">효</span><span>HYOJE / 2026</span></a><nav><a href="#journey">JOURNEY</a><a href="#works">WORKS</a><button className="chat-pill" onClick={() => setChatOpen(true)}>효제에게 묻기 <span>↗</span></button></nav></header>
    <aside className="side-nav" aria-label="페이지 바로가기"><span className="side-nav-title">HYOJE<br /><small>PROFILE</small></span><a href="#top">01 <span>INTRO</span></a><a href="#journey">02 <span>JOURNEY</span></a><a href="#works">03 <span>WORKS</span></a><a href="#proof">04 <span>PROOF</span></a><a href="#next">05 <span>NEXT</span></a></aside>
    <section className="hero personal-hero" id="top"><div className="hero-copy"><p className="kicker">DIGITAL SELF-PORTRAIT · ICT융합학부 1학년</p><h1>안녕하세요,<br /><em>효제입니다.</em></h1><p className="hero-text">디자인으로 시작해 코드로 확장하고,<br />직접 필요한 것을 만들어 왔습니다.</p><button className="primary" onClick={() => document.getElementById('works')?.scrollIntoView({ behavior: 'smooth' })}>만든 것부터 보기 <span>↓</span></button></div><div className="hero-art personal-art"><div className="portrait-orbit" /><div className="portrait-core"><span>H</span><small>HYOJE</small></div><div className="floating-label label-design">DESIGN</div><div className="floating-label label-code">CODE</div><div className="floating-label label-ai">AI / AUTOMATION</div><div className="sticker">01<br /><small>YEAR</small></div></div></section>
    <section className="identity" id="about"><div><span className="strip-label">ONE-LINE PROFILE</span><h2>관심을<br /><em>결과물로 바꾸는</em><br />새내기</h2></div><div className="identity-copy"><p>울산대학교 ICT융합학부 1학년 김효제입니다. 포스터를 만들던 손으로 웹 화면을 설계하고, 배운 Python으로 반복 작업을 자동화했습니다. 아직 완성된 개발자는 아니지만, 궁금한 것을 직접 만들어 확인하는 사람입니다.</p><div className="identity-stats"><div><strong>01</strong><span>학년</span></div><div><strong>230</strong><span>TOPCIT 점수</span></div><div><strong>04</strong><span>주요 프로젝트</span></div></div></div></section>
    <section className="archive" id="journey"><div className="chapter-intro"><span className="strip-label">2026.02 — 2026.08 / JOURNEY</span><h2>학기와 방학 동안<br /><em>직접 해본 일들</em></h2><p>경험의 순서가 곧 효제의 방향이 되었습니다. 디자인에서 개발로, 관심에서 실제 작동하는 결과물로 이어진 기록입니다.</p><span className="scroll-cue">SCROLL TO EXPLORE ↓</span></div><div className="chapter-stack">{semesters.map((entry, index) => <article className={`story-chapter ${entry.color}`} key={entry.period}><div className="chapter-no">{String(index + 1).padStart(2, '0')}</div><div className="chapter-copy"><span className="detail-label">{entry.period}</span><h3>{entry.title}</h3><p>{entry.text}</p><div className="detail-tags">{entry.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><span className="chapter-proof">HYOJE LOG / {index + 1} of {semesters.length}</span></div><div className="chapter-symbol">{index === 0 ? '✦' : index === 1 ? '↗' : index === 2 ? '♫' : index === 3 ? '</>' : index === 4 ? '?' : '∞'}</div></article>)}</div></section>
    <section className="projects project-cases" id="works"><div className="section-heading"><div><span className="strip-label">SELECTED WORKS / CASE FILES</span><h2>내가 한 일을<br /><em>결과물로 확인하세요.</em></h2></div><p className="section-intro">컴퓨터에 남아 있던 저장소와 캡처를 바탕으로, 효제가 실제로 시도하고 만든 프로젝트를 정리했습니다.</p></div><div className="case-layout"><div className="case-list">{projects.map((project) => <a href={`#case-${project.id}`} className="case-index" key={project.id}><span>{project.no}</span><div><small>{project.type}</small><strong>{project.title}</strong></div><span>↗</span></a>)}</div><div className="case-detail-list">{projects.map((project) => <article className="case-detail" id={`case-${project.id}`} key={project.id}><div className="case-detail-copy"><span className="project-index">{project.no} / {project.type}</span><h3>{project.title}</h3><p className="case-summary">{project.summary}</p><dl><div><dt>내가 한 일</dt><dd>{project.did}</dd></div><div><dt>만든 방식</dt><dd>{project.how}</dd></div><div><dt>남은 결과</dt><dd>{project.result}</dd></div></dl><div className="project-meta">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div><div className="case-visual"><img src={project.image} alt={`${project.title} 결과물`} /><img className="case-thumb" src={project.thumb} alt={`${project.title} 보조 이미지`} /></div></article>)}</div></div></section>
    <section className="activities" id="proof"><div className="section-heading"><div><span className="strip-label">PROOF / BEYOND THE CLASSROOM</span><h2>배운 것을<br /><em>확인할 수 있는 기록</em></h2></div><p className="section-intro">점수와 수료, 협업과 대외활동까지 결과물 옆에 근거를 남겼습니다.</p></div><div className="activity-grid"><article className="activity-card"><div className="activity-top"><span>01</span><small>2026 · SCORE</small></div><p className="activity-label">ACHIEVEMENT</p><h3>TOPCIT 230점</h3><p>정보기술 역량을 점검하는 TOPCIT에서 230점을 받았습니다. 현재 위치를 확인하고 다음 학습 목표를 세우는 기준이 됐습니다.</p><div className="activity-line" /></article><article className="activity-card"><div className="activity-top"><span>02</span><small>2026.05.30 · 12H</small></div><p className="activity-label">CERTIFICATE</p><h3>블록 OS + 생성형 AI 창작 워크숍</h3><p>울산대학교 특강과 워크숍을 12시간 수료했습니다. AI를 활용해 아이디어를 인터랙티브 콘텐츠로 바꾸는 실험을 진행했습니다.</p><div className="activity-line" /></article><article className="activity-card"><div className="activity-top"><span>03</span><small>2026.07 · TEAM</small></div><p className="activity-label">COMMUNITY</p><h3>GaonSplint 1기</h3><p>팀원들과 업무 일지를 작성하고 GitHub 조직에서 협업했습니다. 혼자 공부하던 코드를 함께 만드는 흐름으로 확장했습니다.</p><div className="activity-line" /></article></div><div className="credential-link"><span>수료증 원본</span><a href="/evidence/certificate-hyoje.pdf" target="_blank" rel="noreferrer">증거 문서 열기 ↗</a></div></section>
    <section className="future" id="next"><span className="strip-label">NEXT EXPERIMENT</span><h2>다음에는<br /><em>AI 페르소나</em>를 만듭니다.</h2><p>이 사이트는 효제의 기록을 대화형 경험으로 확장한 첫 번째 프로토타입입니다. 다음 단계에서는 프로젝트의 과정과 선택까지 더 깊이 보여주겠습니다.</p><button className="primary" onClick={() => setChatOpen(true)}>AI 효제 만나기 <span>↗</span></button></section><footer><span>효제의 디지털 자기소개</span><span>울산대학교 ICT융합학부 · 2026</span></footer><button className="floating-chat" aria-label="AI 효제 열기" onClick={() => setChatOpen(true)}>✦ <span>AI 효제에게 묻기</span></button>
    {chatOpen && <div className="chat-backdrop" onClick={() => setChatOpen(false)}><section className="chat-panel" onClick={(event) => event.stopPropagation()}><div className="chat-head"><div><span className="status-dot" /> 효제의 AI 페르소나</div><button onClick={() => setChatOpen(false)} aria-label="챗봇 닫기">×</button></div><div className="chat-context">효제의 실제 프로젝트 기록을 바탕으로 답해요</div><div className="quick-prompts"><button onClick={() => askBot('효제가 실제로 만든 프로젝트를 알려줘')}>프로젝트 소개</button><button onClick={() => askBot('코지커피 프로젝트에서 효제가 한 일은?')}>한 일 보기</button></div><div className="messages">{messages.map((message, index) => <div className={`message ${message.role}`} key={`${message.role}-${index}`}>{message.content}</div>)}{loading && <div className="message assistant">기록을 살펴보는 중이에요…</div>}</div><div className="chat-input"><input value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') askBot(); }} placeholder="효제에 대해 물어보세요" aria-label="챗봇 질문" /><button onClick={() => askBot()} aria-label="질문 보내기">↑</button></div></section></div>}
  </main>;
}
