'use client';

import { useState } from 'react';

type Message = { role: 'user' | 'assistant'; content: string };
const profile = `효제는 울산대학교 ICT융합학부 1학년이다. 2026년 상반기에는 코지커피 리뉴얼 포스터와 메뉴판 배너, 인스타그램 콘텐츠를 디자인했고, Ada와 Python을 배우기 시작했다. 트랙페스타와 ICT융합학부 졸업작품 전시를 경험했으며, 오류를 직접 지적하는 AI 시스템에 깊은 인상을 받았다. 하반기에는 React, Next.js, TypeScript, GitHub Actions, Docker를 익혔고, Python 크롤러와 GitHub Actions를 연결해 학내 공지 알림을 Discord로 보내는 자동화 시스템을 만들었다. 산책, 아이돌 음악, 드라마를 좋아하고, AI를 활용한 인터랙티브 페르소나를 만들고 있다.`;

const timeline = [
  { date: '02.04', label: 'DESIGN', title: '코지커피의 새로운 시작', text: '재오픈한 코지커피의 리뉴얼을 위해 포스터와 메뉴판 배너를 디자인했습니다.', tags: ['포스터', '메뉴판 배너'], color: 'yellow' },
  { date: '03', label: 'BEGIN', title: '울산대학교 ICT융합학부 입학', text: '친구와 동아리 면접에 지원하고, 통학 버스에서 음악과 드라마를 즐기며 새로운 일상을 시작했습니다.', tags: ['신입생', '동아리', '산책'], color: 'green' },
  { date: '04', label: 'CULTURE', title: '좋아하는 것을 기록하는 사람', text: '이쿠타 리라 내한 공연 기대평을 작성하며 음악과 문화생활에 대한 관심을 표현했습니다.', tags: ['음악', '공연', '기대평'], color: 'pink' },
  { date: '05', label: 'LEARN', title: '배움의 범위를 넓히다', text: '트랙페스타에서 학과 부스와 선배 토크를 경험하고, Python 자료구조·웹 스크래핑·Spring Boot·JPA를 탐구했습니다.', tags: ['Python', 'Spring Boot', 'JPA'], color: 'blue' },
  { date: '06', label: 'QUESTION', title: '좋은 AI란 무엇일까?', text: '졸업작품 전시에서 학생의 오류를 직접 지적하는 AI 시스템을 리뷰했습니다. 단순히 답하는 AI보다 함께 성장시키는 AI에 관심을 갖게 된 순간입니다.', tags: ['졸업작품 전시', 'AI 리뷰'], color: 'purple' },
  { date: '07', label: 'BUILD', title: '팀으로 만들고, 매일 기록하다', text: '김현주·한주희·손승환·박서연 팀원들과 프로젝트를 진행하며 업무 일지를 작성했습니다. React, Next.js, TypeScript와 GitHub Actions를 실습했습니다.', tags: ['협업', 'React', 'TypeScript'], color: 'orange' },
  { date: '08', label: 'AUTOMATE', title: '반복되는 일을 코드로 바꾸다', text: 'Python 크롤러와 GitHub Actions를 연결해 학내 공지 업데이트를 Discord로 자동 전송하는 시스템을 구축했습니다.', tags: ['크롤러', '자동화', 'Discord'], color: 'teal' },
];
const activities = [
  { label: 'REAL CLIENT', title: '부모님 카페 인스타그램 제작', text: '코지커피의 분위기와 리뉴얼 소식을 전달하기 위해 인스타그램 콘텐츠 제작에도 참여했습니다. 디자인이 실제 공간과 사람을 연결하는 경험이었습니다.', meta: '2026.02 · @cozycoffee_gulwha' },
  { label: 'PROGRAM', title: '로컬 AI 메이커스랩 지원', text: 'Python을 막 배우기 시작한 1학년의 열정으로 지역 기반 AI 프로젝트 프로그램에 지원했습니다.', meta: '2026.06 · 지원' },
  { label: 'COMMUNITY', title: 'GaonSplint 1기 합류', text: '개발을 배우는 사람들과 연결되어 GitHub 조직에 합류하고, 함께 만드는 방식과 협업 흐름을 경험했습니다.', meta: '2026.07 · 활동' },
  { label: 'TEAM PROJECT', title: '김현주·한주희·손승환·박서연과 협업', text: '매일 업무 일지를 작성하며 역할과 진행 상황을 기록하고, React·Next.js·TypeScript 기반 프로젝트를 수행했습니다.', meta: '2026.07 · 팀 프로젝트' },
];

export default function Home() {
  const [active, setActive] = useState(0); const [chatOpen, setChatOpen] = useState(false); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [messages, setMessages] = useState<Message[]>([{ role: 'assistant', content: '안녕하세요. 저는 효제의 2026년 성장 기록을 안내하는 AI 페르소나입니다. 효제가 무엇을 배우고, 만들고, 좋아하는지 물어보세요.' }]);
  const askBot = async (preset?: string) => { const prompt = (preset ?? input).trim(); if (!prompt || loading) return; setInput(''); setMessages((current) => [...current, { role: 'user', content: prompt }]); setLoading(true); try { const response = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ prompt, context: profile }) }); const data = await response.json(); setMessages((current) => [...current, { role: 'assistant', content: data.message ?? '잠시 후 다시 시도해 주세요.' }]); } catch { setMessages((current) => [...current, { role: 'assistant', content: '챗봇 연결을 확인하고 있어요.' }]); } finally { setLoading(false); } };
  const item = timeline[active];
  return <main className="site-shell"><header className="topbar"><a className="brand" href="#top"><span className="brand-mark">효</span><span>HYOJE / 2026</span></a><nav><a href="#archive">ARCHIVE</a><a href="#identity">ABOUT ME</a><button className="chat-pill" onClick={() => setChatOpen(true)}>효제에게 묻기 <span>↗</span></button></nav></header>
    <section className="hero personal-hero" id="top"><div className="hero-copy"><p className="kicker">DIGITAL SELF-PORTRAIT · ICT융합학부 1학년</p><h1>안녕하세요,<br /><em>효제입니다.</em></h1><p className="hero-text">디자인으로 시작해 코드로 확장하고,<br />AI와 자동화로 나의 가능성을 실험합니다.</p><button className="primary" onClick={() => document.getElementById('archive')?.scrollIntoView({ behavior: 'smooth' })}>효제의 기록 열기 <span>↓</span></button></div><div className="hero-art personal-art"><div className="portrait-orbit" /><div className="portrait-core"><span>H</span><small>HYOJE</small></div><div className="floating-label label-design">DESIGN</div><div className="floating-label label-code">CODE</div><div className="floating-label label-ai">AI / AUTOMATION</div><div className="sticker">01<br /><small>SEMESTER</small></div></div></section>
    <section className="identity" id="identity"><div><span className="strip-label">WHO I AM</span><h2>디자인과 기술<br />사이에서 배우는 중</h2></div><div className="identity-copy"><p>저는 울산대학교 ICT융합학부 1학년 효제입니다. 처음에는 포스터와 배너를 만들며 시각적으로 생각했고, 지금은 Python과 웹 기술을 배우며 아이디어가 실제로 작동하게 만드는 방법을 익히고 있습니다.</p><div className="identity-stats"><div><strong>01</strong><span>학년</span></div><div><strong>07</strong><span>개월의 기록</span></div><div><strong>∞</strong><span>계속할 실험</span></div></div></div></section>
    <section className="archive" id="archive"><div className="section-heading"><div><span className="strip-label">MY 2026 ARCHIVE</span><h2>효제의 성장<br />타임라인</h2></div><span className="step-count">{String(active + 1).padStart(2, '0')} / 07</span></div><div className="archive-layout"><div className="timeline-list">{timeline.map((entry, index) => <button className={`timeline-item ${index === active ? 'active' : ''}`} key={entry.date} onClick={() => setActive(index)}><span className="timeline-date">{entry.date}</span><span><small>{entry.label}</small><strong>{entry.title}</strong></span><span className="timeline-arrow">↗</span></button>)}</div><article className={`archive-detail ${item.color}`}><span className="detail-label">{item.label} / 2026</span><div className="detail-number">{String(active + 1).padStart(2, '0')}</div><h3>{item.title}</h3><p>{item.text}</p><div className="detail-tags">{item.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="detail-note">이 기록이 보여주는 나<br /><strong>{active < 2 ? '만드는 사람' : active < 5 ? '질문하는 사람' : '연결하는 사람'}</strong></div></article></div></section>
    <section className="activities" id="activities"><div className="section-heading"><div><span className="strip-label">BEYOND THE CLASSROOM</span><h2>교실 밖에서<br />확장한 경험</h2></div><p className="section-intro">배운 것을 혼자 쌓아두지 않고, 사람·프로그램·공모전 속에서 직접 시험해 본 기록입니다.</p></div><div className="activity-grid">{activities.map((activity, index) => <article className="activity-card" key={activity.title}><div className="activity-top"><span>{String(index + 1).padStart(2, '0')}</span><small>{activity.meta}</small></div><p className="activity-label">{activity.label}</p><h3>{activity.title}</h3><p>{activity.text}</p><div className="activity-line" /></article>)}</div></section>
    <section className="values"><div><span className="strip-label">MY SIGNALS</span><h2>효제를 설명하는<br />네 가지 신호</h2></div><div className="signal-grid"><article><strong>01</strong><h3>만들기</h3><p>포스터부터 웹까지, 생각을 눈에 보이는 결과물로 만듭니다.</p></article><article><strong>02</strong><h3>배우기</h3><p>Ada, Python, Java, React를 배우며 모르는 영역을 넓힙니다.</p></article><article><strong>03</strong><h3>연결하기</h3><p>코드와 서비스, 팀원과 아이디어를 연결해 작동하는 흐름을 만듭니다.</p></article><article><strong>04</strong><h3>돌아보기</h3><p>상담, 에세이, 업무 일지로 경험을 기록하고 다음 선택을 준비합니다.</p></article></div></section>
    <section className="future"><span className="strip-label">NEXT EXPERIMENT</span><h2>다음에는<br /><em>AI 페르소나</em>를 만듭니다.</h2><p>Google Opal과 인터랙티브 기술을 활용해, 효제의 기록과 관심사를 대화형 경험으로 확장합니다. 이 사이트 자체가 그 실험의 첫 번째 프로토타입입니다.</p><button className="primary" onClick={() => setChatOpen(true)}>AI 효제 만나기 <span>↗</span></button></section><footer><span>효제의 디지털 자기소개</span><span>울산대학교 ICT융합학부 · 2026</span></footer><button className="floating-chat" aria-label="AI 효제 열기" onClick={() => setChatOpen(true)}>✦ <span>AI 효제에게 묻기</span></button>
    {chatOpen && <div className="chat-backdrop" onClick={() => setChatOpen(false)}><section className="chat-panel" onClick={(event) => event.stopPropagation()}><div className="chat-head"><div><span className="status-dot" /> 효제의 AI 페르소나</div><button onClick={() => setChatOpen(false)} aria-label="챗봇 닫기">×</button></div><div className="chat-context">효제의 실제 기록을 바탕으로 답해요</div><div className="quick-prompts"><button onClick={() => askBot('효제는 어떤 사람인가요?')}>효제 소개</button><button onClick={() => askBot('효제가 가장 인상 깊게 배운 것은 무엇인가요?')}>성장 기록</button></div><div className="messages">{messages.map((message, index) => <div className={`message ${message.role}`} key={`${message.role}-${index}`}>{message.content}</div>)}{loading && <div className="message assistant">기록을 살펴보는 중이에요…</div>}</div><div className="chat-input"><input value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') askBot(); }} placeholder="효제에 대해 물어보세요" aria-label="챗봇 질문" /><button onClick={() => askBot()} aria-label="질문 보내기">↑</button></div></section></div>}</main>;
}
