'use client';

import { useState } from 'react';

type Message = { role: 'user' | 'assistant'; content: string };
const profile = `김효제는 울산대학교 ICT융합학부 1학년으로, 2026년 1학기부터 여름방학까지 디자인과 개발을 함께 시도했다. 부모님 카페 코지커피의 포스터·메뉴판 배너·인스타그램 콘텐츠를 만들었고, React·TypeScript 기반 식단 웹앱, 부울경 AI 해커톤 아이디어 OceanSnap, AI 메이커스랩 프로젝트, 게임잼 프로젝트를 경험했다. 게임잼에서는 대상을 받았고, Ada·Python·Java Spring Boot·JPA를 학습했으며 TOPCIT 230점을 받았다.`;
const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? '';
const assetPath = (path: string) => `${basePath}${path}`;
const localAnswer = (prompt: string) => {
  if (prompt.includes('코지커피')) return '부모님 카페 코지커피의 분위기와 필요한 정보를 관찰한 뒤 포스터, 메뉴판 배너, 로고, 인스타그램 콘텐츠를 제작했습니다. 실제 의뢰를 시각물로 완성한 작업입니다.';
  if (prompt.includes('게임잼') || prompt.includes('Unity')) return '게임잼에서는 Unity를 사용해 팀원들과 게임 콘텐츠를 제작했습니다. 제한된 시간 안에 플레이 테스트와 발표까지 진행했고, 대상이라는 결과를 얻었습니다.';
  if (prompt.includes('OceanSnap') || prompt.includes('해양')) return 'OceanSnap은 부울경 AI 해커톤에서 해양 쓰레기 문제를 해결할 아이디어로 고려한 프로젝트입니다. 시민 신고와 이미지 분석을 연결하는 사용자 흐름을 구상했으며 수상작은 아닙니다.';
  return '코지커피 리뉴얼, 오늘의 식단 웹앱, OceanSnap 해양 쓰레기 분석 아이디어, AI 메이커스랩, Unity 게임잼을 만들거나 기획했습니다. 게임잼은 Unity로 제작해 대상을 받았고, OceanSnap은 해커톤 참가 아이디어로 수상작이 아닙니다.';
};
const semesters = [
  { period: '1학기 시작 · 02–03', title: '디자인과 대학생활을 동시에 시작', text: '코지커피 리뉴얼 포스터·메뉴판 배너를 만들며 실제 사용자를 생각하는 디자인을 경험했습니다. 울산대학교 ICT융합학부에 입학하고 동아리에도 도전했습니다.', tags: ['코지커피', '입학', '동아리'], color: 'yellow' },
  { period: '1학기 학습 · 04–05', title: '관심을 기술의 언어로 넓히다', text: '음악과 공연을 콘텐츠로 기록하는 한편, Python 자료구조·웹 스크래핑·Spring Boot·JPA를 공부했습니다. 트랙페스타에서 전공과 선배들의 실제 이야기도 만났습니다.', tags: ['콘텐츠', 'Python', 'Spring Boot'], color: 'blue' },
  { period: '1학기 후반 · 06', title: 'AI를 바라보는 기준을 세우다', text: '졸업작품 전시에서 오류를 직접 지적하는 AI 시스템을 리뷰했습니다. “답하는 AI”를 넘어 사용자의 다음 행동을 돕는 AI를 만들고 싶다는 방향이 생겼습니다.', tags: ['AI 전시', '리뷰', '문제 정의'], color: 'purple' },
  { period: '여름방학 · 07–08', title: 'Unity로 완성하고, 대상까지 받다', text: '게임잼에서 팀원들과 Unity를 사용해 게임 콘텐츠를 제작했습니다. 제한된 시간 안에 아이디어를 플레이 가능한 형태로 만들고, 테스트와 발표를 거쳐 대상을 받았습니다.', tags: ['게임잼', 'Unity', '대상'], color: 'teal' },
];
const projects = [
  { id: 'cozy', no: '01', type: 'REAL CLIENT / DESIGN', title: '코지커피 리뉴얼 콘텐츠', summary: '부모님 카페의 재오픈을 알리는 실제 콘텐츠를 만들었습니다.', did: '포스터·메뉴판 배너·인스타그램 콘텐츠 제작', how: '카페의 따뜻한 분위기와 메뉴 정보를 관찰한 뒤, 갈색 계열의 브랜드 톤과 읽기 쉬운 정보 배치를 적용했습니다.', result: '실제 매장과 SNS에 사용할 수 있는 디자인 결과물', image: assetPath('/evidence/cozycoffee-poster.png'), thumb: assetPath('/evidence/cozycoffee-logo.png'), tags: ['실제 의뢰', '시각 디자인', 'SNS'] },
  { id: 'meal', no: '02', type: 'TEAM / FRONTEND', title: '오늘의 식단 웹앱', summary: '팀 프로젝트로 React·TypeScript 기반 식단 화면을 제작했습니다.', did: '식단 홈 화면과 재사용 가능한 UI 컴포넌트 구현', how: '화면을 아침·점심·저녁 카드로 나누고, 사용자가 오늘의 메뉴와 예상 비용을 빠르게 파악하도록 정보 우선순위를 정했습니다.', result: '직접 눌러볼 수 있는 웹 화면과 협업 경험', image: assetPath('/evidence/vacation-project-home.png'), thumb: '', tags: ['React', 'TypeScript', 'GitHub'] },
  { id: 'ocean', no: '03', type: 'BUSAN–ULSAN AI HACKATHON / IDEA', title: 'OceanSnap 해양 쓰레기 분석', summary: '부울경 AI 해커톤에서 해양 쓰레기 문제를 해결할 아이디어로 고려한 프로젝트입니다.', did: '해양 쓰레기 사진 분석 서비스의 사용자 흐름과 화면 구조 구상', how: '시민 신고 → 이미지 분석 → 결과 확인 → 수거 우선순위 판단으로 이어지는 웹 서비스 흐름을 설계했습니다.', result: '수상작이 아닌, 문제를 기술로 풀어보며 발전시킨 아이디어', image: assetPath('/evidence/oceansnap-icon.png'), thumb: assetPath('/evidence/oceansnap-icon.png'), tags: ['AI 아이디어', 'Next.js', '해커톤 참가'] },
  { id: 'makers', no: '04', type: 'AI MAKERS LAB / PROGRAM', title: 'AI 메이커스랩 프로젝트', summary: '실무형 AI 프로젝트 프로그램에 참여하며 문제 정의부터 서비스 기획까지 경험했습니다.', did: '현직자 인터뷰·고객 문제 정의·서비스 기획·프로토타입 초안·MVP 테스트 참여', how: '4주 일정에 맞춰 문제 정의 → 서비스 기획 → 사용자 테스트 → 해결책 발표의 단계로 프로젝트를 진행했습니다.', result: 'AI를 단순히 사용하는 것을 넘어, 실제 사용자를 위한 서비스로 설계한 경험', image: assetPath('/evidence/ai-project-poster.png'), thumb: assetPath('/evidence/ai-project-roadmap.png'), tags: ['문제 정의', '프로토타입', 'MVP'] },
  { id: 'gamejam', no: '05', type: 'GAME JAM / GRAND PRIZE', title: '게임잼 대회 대상', summary: '팀원들과 Unity로 게임 콘텐츠를 제작하고 대상을 받았습니다.', did: '아이디어 구체화·Unity 게임 제작·팀 협업·플레이 테스트·발표 참여', how: '현장에서 역할을 나누고 Unity로 빠르게 프로토타입을 제작했습니다. 플레이 경험을 점검하며 수정한 뒤 최종 발표까지 완성했습니다.', result: '처음부터 끝까지 팀으로 완성해 수상한 경험', image: assetPath('/evidence/gamejam-award-mosaic.png'), thumb: assetPath('/evidence/gamejam-process.png'), tags: ['Unity', '게임 콘텐츠', '대상'] },
];

export default function Home() {
  const [chatOpen, setChatOpen] = useState(false); const [mobileMenuOpen, setMobileMenuOpen] = useState(false); const [lightbox, setLightbox] = useState<{ src: string; alt: string } | null>(null); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false);
  const [messages, setMessages] = useState<Message[]>([{ role: 'assistant', content: '안녕하세요. 저는 효제의 2026년 기록을 안내하는 AI 페르소나입니다. 어떤 프로젝트를 어떻게 만들었는지 물어보세요.' }]);
  const askBot = async (preset?: string) => {
    const prompt = (preset ?? input).trim();
    if (!prompt || loading) return;
    setInput('');
    setMessages((m) => [...m, { role: 'user', content: prompt }]);
    setLoading(true);
    try {
      const res = await fetch(`${basePath}/api/chat`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ prompt, context: profile }) });
      if (!res.ok) throw new Error('static-pages');
      const data = await res.json();
      setMessages((m) => [...m, { role: 'assistant', content: data.message ?? '기록을 찾지 못했어요.' }]);
    } catch {
      try {
        const staticRes = await fetch(`${basePath}/ai-responses.json`);
        const answers = await staticRes.json() as Record<string, string>;
        const answer = answers[prompt] ?? localAnswer(prompt);
        setMessages((m) => [...m, { role: 'assistant', content: answer }]);
      } catch {
        setMessages((m) => [...m, { role: 'assistant', content: localAnswer(prompt) }]);
      }
    } finally { setLoading(false); }
  };
  return <main className="site-shell portfolio-page">
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">효</span><span>HYOJE / 2026</span></a><button className="menu-toggle" type="button" aria-expanded={mobileMenuOpen} aria-controls="mobile-navigation" onClick={() => setMobileMenuOpen((open) => !open)}>{mobileMenuOpen ? '닫기' : '메뉴'}</button><nav className="desktop-nav"><a href="#why">WHY ME</a><a href="#works">WORKS</a><a href="#proof">PROOF</a><a href={`${basePath}/ai-guide`}>AI GUIDE</a><button className="chat-pill" onClick={() => setChatOpen(true)}>효제에게 묻기 <span>↗</span></button></nav>{mobileMenuOpen && <nav className="mobile-nav" id="mobile-navigation"><a href="#about" onClick={() => setMobileMenuOpen(false)}>ABOUT ME</a><a href="#why" onClick={() => setMobileMenuOpen(false)}>WHY THIS IS ME</a><a href="#works" onClick={() => setMobileMenuOpen(false)}>WORKS</a><a href="#proof" onClick={() => setMobileMenuOpen(false)}>PROOF</a><a href="#next" onClick={() => setMobileMenuOpen(false)}>NEXT</a><a href={`${basePath}/ai-guide`} onClick={() => setMobileMenuOpen(false)}>AI GUIDE ↗</a></nav>}</header>
    <aside className="side-nav" aria-label="전체 목차"><span className="side-nav-title">HYOJE<br /><small>CONTENTS</small></span><div className="side-nav-group"><a href="#top"><b>01</b><span>INTRO</span></a><a href="#about"><b>02</b><span>ABOUT ME</span></a><a href="#why"><b>03</b><span>WHY THIS IS ME</span></a><a href="#journey"><b>04</b><span>JOURNEY</span></a><a href="#works"><b>05</b><span>WORKS</span></a><a href="#proof"><b>06</b><span>PROOF</span></a><a href="#next"><b>07</b><span>NEXT</span></a></div></aside>
    <section className="hero personal-hero" id="top"><div className="hero-copy"><p className="kicker">DIGITAL SELF-PORTRAIT · 2026</p><h1>디지털 기술로<br /><em>저를 표현했습니다.</em></h1><p className="hero-text">저는 관찰한 것을 디자인하고,<br />궁금한 것을 코드와 Unity로 만들며, 팀과 함께 완성합니다.</p><button className="primary" onClick={() => document.getElementById('works')?.scrollIntoView({ behavior: 'smooth' })}>제가 만든 방식 보기 <span>↓</span></button></div><div className="hero-art personal-art"><div className="hero-monogram">HYOJE<span>2026 / ICT</span></div><div className="floating-label label-design">OBSERVE</div><div className="floating-label label-code">BUILD</div><div className="floating-label label-ai">CONNECT</div><div className="sticker">H<br /><small>HYOJE</small></div></div></section>
    <section className="identity" id="about"><div><span className="strip-label">ABOUT HYOJE</span><h2>저는 무엇을<br /><em>어떻게 만드는가</em></h2></div><div className="identity-copy"><p>공모 주제인 “디지털 기술을 활용해 나를 표현한 창의적 콘텐츠”를 제 경험으로 풀었습니다. 포스터, 웹앱, AI 서비스, 게임, 프로그램 참여라는 서로 다른 기록을 하나의 질문으로 연결했습니다. “나는 무엇을 관찰하고, 어떤 방식으로 만들며, 무엇을 끝까지 완성하는가?”</p><div className="identity-stats"><div><strong>01</strong><span>학년</span></div><div><strong>230</strong><span>TOPCIT 점수</span></div><div><strong>05</strong><span>대표 기록</span></div></div></div></section>
    <section className="theme-fit" id="why"><div className="section-heading"><div><span className="strip-label">WHY THIS IS ME</span><h2>다섯 개의 기록,<br /><em>하나의 자기소개</em></h2></div><p className="section-intro">이 사이트에서 작품을 클릭해 보세요. 각각의 결과물이 효제의 어떤 모습을 보여주는지 확인할 수 있습니다.</p></div><div className="theme-grid"><article><span>01 / OBSERVE</span><h3>분위기를 읽습니다</h3><p>코지커피의 공간과 브랜드를 관찰하고, 사람들이 이해하기 쉬운 이미지와 정보로 바꿨습니다.</p></article><article><span>02 / STRUCTURE</span><h3>정보를 정리합니다</h3><p>식단 웹앱의 화면을 사용자의 하루 흐름에 맞게 나누고, 팀과 함께 실제 화면으로 구현했습니다.</p></article><article><span>03 / SOLVE</span><h3>문제를 기술로 봅니다</h3><p>OceanSnap과 AI 메이커스랩에서 문제를 사용자 흐름과 AI 서비스 구조로 표현했습니다.</p></article><article><span>04 / COMPLETE</span><h3>끝까지 완성합니다</h3><p>게임잼에서는 제한된 시간 안에 팀원들과 Unity 게임을 완성하고 대상이라는 결과로 증명했습니다.</p></article></div></section>
    <section className="archive" id="journey"><div className="chapter-intro"><span className="strip-label">A SHORT STORY / 2026.02 — 2026.08</span><h2>처음부터 잘한 게 아니라<br /><em>직접 해보며 배웠습니다.</em></h2><p>이 여정은 대표 작품을 이해하기 위한 짧은 배경입니다. 자세한 이야기는 아래 Works에서 결과물 중심으로 확인할 수 있습니다.</p><span className="scroll-cue">A LITTLE BACKSTORY ↓</span></div><div className="chapter-stack">{semesters.map((entry, index) => <article className={`story-chapter ${entry.color}`} key={entry.period}><div className="chapter-no">{String(index + 1).padStart(2, '0')}</div><div className="chapter-copy"><span className="detail-label">{entry.period}</span><h3>{entry.title}</h3><p>{entry.text}</p><div className="detail-tags">{entry.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><span className="chapter-proof">HYOJE LOG / {index + 1} of {semesters.length}</span></div><div className="chapter-symbol">{index === 0 ? '✦' : index === 1 ? '↗' : index === 2 ? '♫' : index === 3 ? '</>' : index === 4 ? '?' : '∞'}</div></article>)}</div></section>
    <section className="projects project-cases" id="works"><div className="section-heading"><div><span className="strip-label">SELECTED WORKS / CASE FILES</span><h2>내가 한 일을<br /><em>결과물로 확인하세요.</em></h2></div><p className="section-intro">프로젝트 목록을 따로 두지 않고, 각 작품의 설명과 실제 제작 화면을 한눈에 볼 수 있도록 구성했습니다.</p></div><div className="case-detail-list">{projects.map((project) => <article className="case-detail" id={`case-${project.id}`} key={project.id}><div className="case-detail-copy"><span className="project-index">{project.no} / {project.type}</span><h3>{project.title}</h3><p className="case-summary">{project.summary}</p><dl><div><dt>무엇을 만들었는가</dt><dd>{project.did}</dd></div><div><dt>왜 시작했는가</dt><dd>{project.summary}</dd></div><div><dt>내가 직접 한 일</dt><dd>{project.did}</dd></div><div><dt>사용한 도구와 기술</dt><dd>{project.tags.join(' · ')}</dd></div><div><dt>실제 결과물</dt><dd>{project.result}</dd></div><div><dt>이 경험이 나를 보여주는 점</dt><dd>{project.how}</dd></div></dl><div className="project-meta">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}{project.id === 'meal' && <a className="project-demo-link" href="https://www.mealpick.store/ingredient-register" target="_blank" rel="noreferrer">오늘의 식단 데모 열기 ↗</a>}</div></div><div className={`case-visual ${project.thumb ? '' : 'single'}`}><button className="evidence-trigger" type="button" onClick={() => setLightbox({ src: project.image, alt: `${project.title} 결과물 원본` })}><img src={project.image} alt={`${project.title} 결과물`} /></button>{project.thumb && <button className="evidence-trigger case-thumb-trigger" type="button" onClick={() => setLightbox({ src: project.thumb, alt: `${project.title} 보조 이미지 원본` })}><img className="case-thumb" src={project.thumb} alt={`${project.title} 보조 이미지`} /></button>}<span className="evidence-hint">이미지를 클릭하면 원본을 봅니다</span></div></article>)}</div></section>
    <section className="activities" id="proof"><div className="section-heading"><div><span className="strip-label">PROOF / BEYOND THE CLASSROOM</span><h2>배운 것을<br /><em>확인할 수 있는 기록</em></h2></div><p className="section-intro">점수와 수료, 수상 결과까지 결과물 옆에 근거를 남겼습니다.</p></div><div className="activity-grid"><article className="activity-card"><div className="activity-top"><span>01</span><small>2026 · SCORE</small></div><p className="activity-label">ACHIEVEMENT</p><h3>TOPCIT 230점</h3><p>정보기술 역량을 점검하는 TOPCIT에서 230점을 받았습니다. 현재 위치를 확인하고 다음 학습 목표를 세우는 기준이 됐습니다.</p><div className="activity-line" /></article><article className="activity-card"><div className="activity-top"><span>02</span><small>2026.05.30 · 12H</small></div><p className="activity-label">CERTIFICATE</p><h3>블록 OS + 생성형 AI 창작 워크숍</h3><p>울산대학교 특강과 워크숍을 12시간 수료했습니다. AI를 활용해 아이디어를 인터랙티브 콘텐츠로 바꾸는 실험을 진행했습니다.</p><div className="activity-line" /></article><article className="activity-card"><div className="activity-top"><span>03</span><small>2026 · AWARD</small></div><p className="activity-label">GAME JAM</p><h3>게임잼 대회 대상</h3><p>팀원들과 제한된 시간 안에 게임 콘텐츠를 완성하고 발표해 대상이라는 결과를 얻었습니다. 함께 만든 과정과 수상 현장을 캡처로 남겼습니다.</p><div className="activity-line" /></article></div><div className="credential-link"><span>수료증 원본</span><a href={assetPath('/evidence/certificate-hyoje.pdf')} target="_blank" rel="noreferrer">증거 문서 열기 ↗</a></div></section>
    <section className="future" id="next"><span className="strip-label">NEXT EXPERIMENT</span><h2>다음에는<br /><em>AI 페르소나</em>를 만듭니다.</h2><p>이 사이트는 효제의 기록을 대화형 경험으로 확장한 첫 번째 프로토타입입니다. 다음 단계에서는 프로젝트의 과정과 선택까지 더 깊이 보여주겠습니다.</p><button className="primary" onClick={() => setChatOpen(true)}>AI 효제 만나기 <span>↗</span></button></section><footer><span>효제의 디지털 자기소개</span><span>울산대학교 ICT융합학부 · 2026</span></footer><button className="floating-chat" aria-label="AI 효제 열기" onClick={() => setChatOpen(true)}>✦ <span>AI 효제에게 묻기</span></button>
    {chatOpen && <div className="chat-backdrop" onClick={() => setChatOpen(false)}><section className="chat-panel" onClick={(event) => event.stopPropagation()}><div className="chat-head"><div><span className="status-dot" /> 효제의 AI 페르소나</div><button onClick={() => setChatOpen(false)} aria-label="챗봇 닫기">×</button></div><div className="chat-context">효제의 실제 프로젝트 기록을 바탕으로 답해요</div><div className="quick-prompts"><button onClick={() => askBot('효제가 실제로 만든 프로젝트를 알려줘')}>프로젝트 소개</button><button onClick={() => askBot('코지커피 프로젝트에서 효제가 한 일은?')}>한 일 보기</button></div><div className="messages">{messages.map((message, index) => <div className={`message ${message.role}`} key={`${message.role}-${index}`}>{message.content}</div>)}{loading && <div className="message assistant">기록을 살펴보는 중이에요…</div>}</div><div className="chat-input"><input value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') askBot(); }} placeholder="효제에 대해 물어보세요" aria-label="챗봇 질문" /><button onClick={() => askBot()} aria-label="질문 보내기">↑</button></div></section></div>}
    {lightbox && <div className="lightbox-backdrop" role="dialog" aria-modal="true" aria-label="결과물 원본 보기" onClick={() => setLightbox(null)}><div className="lightbox-panel" onClick={(event) => event.stopPropagation()}><button className="lightbox-close" type="button" onClick={() => setLightbox(null)} aria-label="원본 이미지 닫기">×</button><img src={lightbox.src} alt={lightbox.alt} /><p>원본 이미지 · 닫으려면 바깥을 누르세요</p></div></div>}
  </main>;
}
